# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: image-manager
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters
provider:
  name: aws
  runtime: python3.8
  timeout: 60

# you can overwrite defaults here
#  stage: dev
  region: ap-northeast-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: arn:aws:s3:::sabian-symbols/*
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: arn:aws:s3:::image-manager-rubyfmzk/*

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  resize_put_sabian_images:
    handler: handler.resize_put_sabian_images
    layers:
      - arn:aws:lambda:ap-northeast-1:#{AWS::AccountId}:layer:python-pillow:1
  resize_put_sabian_images_by_event:
    handler: handler.resize_put_sabian_images_by_event
    layers:
      - arn:aws:lambda:ap-northeast-1:#{AWS::AccountId}:layer:python-pillow:1
    events:
      - s3:
          bucket: image-manager-rubyfmzk
          events:
            - "s3:ObjectCreated:*"
          rules:
            - prefix: sabian-symbols/full/
            - suffix: .jpg
          existing: true
  collage_object_white_transparent:
    handler: handler.collage_object_white_transparent
    layers:
      - arn:aws:lambda:ap-northeast-1:#{AWS::AccountId}:layer:python-pillow:1
    events:
      - s3:
          bucket: image-manager-rubyfmzk
          events:
            - "s3:ObjectCreated:*"
          rules:
            - prefix: public/collage/object/
            - suffix: '.jpg'
          existing: true
      - s3:
          bucket: image-manager-rubyfmzk
          events:
            - "s3:ObjectCreated:*"
          rules:
            - prefix: public/collage/object/
            - suffix: '.jpeg'
          existing: true
      - s3:
          bucket: image-manager-rubyfmzk
          events:
            - "s3:ObjectCreated:*"
          rules:
            - prefix: public/collage/object/
            - suffix: '.png'
          existing: true

# you can add CloudFormation resource templates here
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: image-manager-rubyfmzk
        CorsConfiguration:
          CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD, PUT, POST]
            AllowedOrigins: ['*']
    ImageResourceS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: image-manager-rubyfmzk
        PolicyDocument:
          Statement:
            - Sid: FullSizeSabianImage
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource: "arn:aws:s3:::image-manager-rubyfmzk/sabian-symbols/full/*"
              Condition:
                StringLike:
                  aws:Referer:
                    - https://sabian-calculator.com/*
                    - https://*.sabian-calculator.com/*
                    - http://localhost:*/*
            - Sid: UploadImage
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              - s3:PutObject
              Resource: "arn:aws:s3:::image-manager-rubyfmzk/public/*"
              Condition:
                StringLike:
                  aws:Referer:
                    - https://*opyxz.cloudfront.net/*

 # Outputs:
 #    NewOutput:
 #      Description: "Description for the output"
 #      Value: "Some output value"
